version: '3'
services:
  web_app:
    build: 
      context: ./web-app
      dockerfile: ./Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
      - machine_learning_client
    environment:
      FLASK_APP: web-app/app.py

  machine_learning_client:
    build:
      context: ./machine_learning_client
      dockerfile: ./Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
    environment:
      FLASK_APP: machine-learning-client/app.py

  mongodb:
    image: mongo
    ports:
      - "27017:27017"