version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - "4999:4999"
  machine-learning-client:
    build: ./machine-learning-client
    depends_on:
      - mongodb
  web-app:
    build: ./web-app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - machine-learning-client
