name: CI for Machine Learning Client

on:
  push:
    branches: [main, master]
  pull_request:
   types: [opened, closed]
   branches: [main, master]

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r machine_learning_client/requirements.txt
        pip install pytest
        pip install pylint black
    #- name: Run Pylint
      #run: pylint machine_learning_client/app.py --ignore-patterns='.*\.pb2\.py,.*\.pb2_grpc\.py'
    - name: Run Black (Check mode)
      run: black --check machine_learning_client/
    - name: Run tests
      run: pytest tests/ml_app_tests.py
